### ISSUE TITLE
Figure out repo settings

### ISSUE THREAD

**Issue by adhurjaty** [The-Trust-Assembly/trust-assembly#2]
- How do we want to manage contributions to the repository?
- Merge, rebase or squash and merge PRs into main?
- What determines acceptability to merge?
- Disallow pushes directly to main
- Set up auto-delete branch on merge to main
- Set up vulnerability detection? (Dependabot, snyk, etc.)
- Codify this in CONTRIBUTING.md
  - Code review best practices
  - Commit message conventions
  - Branch naming conventions

**Comment by adhurjaty** [comment]
Looking at [Google's engineering practices](https://google.github.io/eng-practices/). I don't think we have to go full-corporate in terms of commit message formatting etc., but would be good to have some guidelines for contributing.

Do we want branch naming guidelines? @time.e.less had indicated `feature_yourname_shortname` as his preference, should we stick with that?

I prefer working with atomic commits (no commit leaves the system in a broken state or failing tests)

Merge, rebase, or squash and merge PRs?

**Comment by maxtriano** [comment]
@adhurjaty No opinion beyond that we squash and merge for PRs to main at my job and I like it, keeps main's history cleaner.

**Comment by adhurjaty** [comment]
> @adhurjaty No opinion beyond that we squash and merge for PRs to main at my job and I like it, keeps main's history cleaner.

I'm good with committing to that at least for now

**Comment by Melvillian** [comment]
merged in #8
