### ISSUE TITLE
Research spike: MVP architecture

### ISSUE THREAD

**Issue by adhurjaty** [The-Trust-Assembly/trust-assembly#7]
Let's figure out how we want to structure our project to fit our needs for the MVP version of the application.
Known components:
- Wiki frontend
- Backend (stick with deno, or does it make sense to switch?)
- Database (looks like we're going with supabase)
- Browser extension

How do we want to serve the Wiki? Single page app? Server-side rendered?
Should we think about incorporating Nextjs, Nuxt, (other popular js metaframeworks)?
We know that the browser extension will need to make calls to the backend, so it must be capable of exposing API endpoints

Acceptance criteria
- A document or conversation with engineers outlining pros/cons of answers to the above questions (and maybe more)

**Comment by adhurjaty** [comment]
How do we feel about React for the Wiki frontend? I imagine the UI can get pretty complex as we start having to deal with showing different edits from different users. React does add a lot of bloat, but I have the most experience using it. How about the other team members?

**Comment by Melvillian** [comment]
@adhurjaty @maxtriano I am almost entirely a backend developer, so I do not have production experience with React. However, I'm willing to learn if you're willing to put up with me while I learn! I think this would mean I'm going to try to review your React PR's, but for the first couple months they're going to be mostly me asking questions about why certain things are the way they are, and less about pointing out the proper way to do things.

My only hesitation with using React and building a wiki from scratch is that, given wiki is like 20+ years old, shouldn't there be an existing tried-and-true tool for building wikis?

:goes out and searched for react wiki libraries...

wow, i couldn't find anything usable by use. That's surprising! OK looks like we're building it from scratch. I was going to suggest we take some off-the-shelf-wiki package like whatever they use to create [Fandom wiki's](https://www.fandom.com/), but that feels too rigid for the rich app I see us building here.

**Comment by adhurjaty** [comment]
I've been hearing that [shadcn](https://ui.shadcn.com/) is a potentially good starting point for UIs. They have a [wiki template](https://v0.dev/t/pf1f2ymCXpi) (requires a free account to see the code).

Other possibilities are Bootstrap or MaterialUI. Both are very opinionated, but I have worked with both. Bootstrap is a bit dated and all Material sites look the same. Shadcn is built on [Tailwind](https://tailwindcss.com/) and you just copy and paste their components into your library, so there's a lot of flexibility. I've worked with Tailwind a bit and I like the dev experience, but there's the tradeoff of more time up front getting the design language locked in.

We don't have to decide yet how we want our styling to work. I would like to see some UI mockups before committing to any one of these

**Comment by maxtriano** [comment]
I'm also a backend/systems guy so I have very little opinion on webdev matters, I'll defer to you @adhurjaty.

**Comment by Melvillian** [comment]
@adhurjaty from talking with frontend coworkers/friends, I'd say it's hard to go wrong with Tailwind. That's what I would choose were I go to build a frontend.

I don't have any strong thoughts on shadcn vs. its competitors. The choice is yours.

**Comment by adhurjaty** [comment]
Looks like we're going with
- Deno API backend
- React frontend, statically served from the deno server, making client-side HTTP or TRPC calls to the API
- Postgres database (maybe supabase)
- Boring bomb: for now should exist as part of the API or a CLI accessible within the docker container
